### ISSUE TITLE
Generated certs dont pass C parsing // wrong CBOR data declaration

### ISSUE THREAD

**Issue by SeriousD** [connctd/smolcert#3]
The generated certificates doesnt match the [specification](https://github.com/smolcert/smolcert-go/blob/master/spec.cddl). 
Datafields that should be arrays are stored as maps. 

Possible fix:
 Change [this](https://github.com/smolcert/smolcert-go/blob/1204ec8872f537073d304df5aaa2ee72eef6baef/extensions.go#L15) ,[this](https://github.com/smolcert/smolcert-go/blob/1204ec8872f537073d304df5aaa2ee72eef6baef/certificates.go#L37) and [this line](https://github.com/smolcert/smolcert-go/blob/1204ec8872f537073d304df5aaa2ee72eef6baef/certificates.go#L109) to   `` _interface{} `cbor:",toarray"` ``

**Comment by dereulenspiegel** [comment]
Fixed by PR #4
